{
 "title": "Fum al Port",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Contaminación partículas 2.5 PM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "C'an pastilla / Bartomeu Riutort 25",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "68453" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Gral Antoni Barceló 28 / Portopí",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "72964" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "El Terreno / Garita 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "74349" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "La Calatraba / Parc de la Mar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "74660" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Canamunt / Moliners 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "68449" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Canamunt / Plaza del Cuadrado",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "68451" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Paseo Marítimo / Gabriel Roca 31",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "query": "SELECT mean(\"74670\") FROM \"pm25\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "74670" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cas Català / Platja de Chicanso",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "query": "SELECT mean(\"74808\") FROM \"pm25\" WHERE \"74808\"<40 AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "74808" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pere Garau / Pere Llobera 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "74662" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Es Jonquet / Plaza Vapor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "77131" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Paseo Marítimo / Gabriel Roca 26",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "query": "SELECT mean(\"83137\") FROM \"pm25\" WHERE \"83137\"<40 AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "83137" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barcos atracados",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Nº de barcos",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vessels",
     "select": [
      [
       { "params": [ "vessels" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barcos atracados",
   "type": "stat",
   "description": "Más de 200 m de eslora",
   "gridPos": { "h": 5, "w": 1, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "alarms",
     "query": "SELECT vessels FROM vessels ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "zone" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Typos de barcos",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 1, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vessels_333",
     "query": "SELECT count(\"name\") FROM \"vessels_333\"  WHERE $timeFilter  GROUP BY \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Contaminación partículas 10 PM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "C'an pastilla / Bartomeu Riutort 25",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "query": "SELECT mean(\"68453\") FROM \"pm10\" WHERE \"68453\"<100 AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "68453" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Gral Antoni Barceló 28 / Portopí",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "72964" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "El Terreno / Garita 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "query": "SELECT mean(\"74349\") FROM \"pm10\" WHERE \"74349\"<45 AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "74349" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "La Calatraba / Parc de la Mar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "74660" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Canamunt / Moliners 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "68449" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Canamunt / Plaza del Cuadrado",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "68451" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Paseo Marítimo / Gabriel Roca 31",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "74670" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cas Català / Platja de Chicanso",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "74808" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pere Garau",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "74662" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pere Garau / Pere Llobera 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "74662" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Es Jonquet / Plaza Vapor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "77131" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Paseo Marítimo / Gabriel Roca 26",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "limit": "200",
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "83137" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incumplimientos",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vessels" ], "type": "tag" }
     ],
     "measurement": "breachs_regulations",
     "query": "SELECT \"rule\", \"cruisers\" FROM \"breachs_regulations\" WHERE $timeFilter GROUP BY time($interval), \"megacruisers\"",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarmas detectadas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "alarms",
     "query": "SELECT count(pm25) FROM \"alarms\" ",
     "select": [
      [
       { "params": [ "zone" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarmas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 23 },
   "targets": [
    {
     "query": "SELECT count(\"pm25\") FROM \"alarms\" GROUP BY \"zone\"\n"
    }
   ]
  },
  {
   "title": "Rosa de los vientos",
   "type": "fatcloud-windrose-panel",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 23 },
   "targets": [
    {
     "alias": "Direcction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "wind_direction" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Velocidad del viento",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 4, "w": 7, "x": 10, "y": 31 } },
  {
   "title": "Lluvia",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pm25",
     "select": [
      [
       { "params": [ "rain" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}